/*
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.ide;


/**
 * Use this class to register ide components.
 */
public class SpringFluentDSLIdeModule extends AbstractSpringFluentDSLIdeModule {
}
