/*
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpringFluentDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/spring/fluent/parser/antlr/internal/InternalSpringFluentDSL.tokens");
	}
}
