package org.xtext.spring.fluent.generator;

import com.google.common.base.Objects;
import java.util.HashMap;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Functions.Function0;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.eclipse.xtext.xbase.lib.Pair;
import org.xtext.spring.fluent.springFluentDSL.Dependencies;
import org.xtext.spring.fluent.springFluentDSL.Dependency;

@SuppressWarnings("all")
public class DependenciesGenerator {
  private static final HashMap<String, String> dependenciesMap = new Function0<HashMap<String, String>>() {
    @Override
    public HashMap<String, String> apply() {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<dependency>");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("<groupId>org.springframework.boot</groupId>");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("<artifactId>spring-boot-starter-actuator</artifactId>");
      _builder.newLine();
      _builder.append("</dependency>");
      _builder.newLine();
      Pair<String, String> _mappedTo = Pair.<String, String>of("SpringActuator", _builder.toString());
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("<dependency>");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("<groupId>org.springframework.boot</groupId>");
      _builder_1.newLine();
      _builder_1.append("    ");
      _builder_1.append("<artifactId>spring-boot-starter-amqp</artifactId>");
      _builder_1.newLine();
      _builder_1.append("</dependency>");
      _builder_1.newLine();
      Pair<String, String> _mappedTo_1 = Pair.<String, String>of("SpringAMQP", _builder_1.toString());
      StringConcatenation _builder_2 = new StringConcatenation();
      _builder_2.append("<dependency>");
      _builder_2.newLine();
      _builder_2.append("    ");
      _builder_2.append("<groupId>org.springframework.boot</groupId>");
      _builder_2.newLine();
      _builder_2.append("    ");
      _builder_2.append("<artifactId>spring-boot-starter-batch</artifactId>");
      _builder_2.newLine();
      _builder_2.append("</dependency>");
      _builder_2.newLine();
      Pair<String, String> _mappedTo_2 = Pair.<String, String>of("SpringBatch", _builder_2.toString());
      StringConcatenation _builder_3 = new StringConcatenation();
      _builder_3.append("<dependency>");
      _builder_3.newLine();
      _builder_3.append("    ");
      _builder_3.append("<groupId>org.springframework.boot</groupId>");
      _builder_3.newLine();
      _builder_3.append("    ");
      _builder_3.append("<artifactId>spring-boot-starter-data-elasticsearch</artifactId>");
      _builder_3.newLine();
      _builder_3.append("</dependency>");
      _builder_3.newLine();
      Pair<String, String> _mappedTo_3 = Pair.<String, String>of("SpringDataElasticsearch", _builder_3.toString());
      StringConcatenation _builder_4 = new StringConcatenation();
      _builder_4.append("<dependency>");
      _builder_4.newLine();
      _builder_4.append("    ");
      _builder_4.append("<groupId>org.springframework.boot</groupId>");
      _builder_4.newLine();
      _builder_4.append("    ");
      _builder_4.append("<artifactId>spring-boot-starter-data-jdbc</artifactId>");
      _builder_4.newLine();
      _builder_4.append("</dependency>");
      _builder_4.newLine();
      Pair<String, String> _mappedTo_4 = Pair.<String, String>of("SpringDataJDBC", _builder_4.toString());
      StringConcatenation _builder_5 = new StringConcatenation();
      _builder_5.append("<dependency>");
      _builder_5.newLine();
      _builder_5.append("    ");
      _builder_5.append("<groupId>org.springframework.boot</groupId>");
      _builder_5.newLine();
      _builder_5.append("    ");
      _builder_5.append("<artifactId>spring-boot-starter-data-jpa</artifactId>");
      _builder_5.newLine();
      _builder_5.append("</dependency>");
      _builder_5.newLine();
      Pair<String, String> _mappedTo_5 = Pair.<String, String>of("SpringDataJPA", _builder_5.toString());
      StringConcatenation _builder_6 = new StringConcatenation();
      _builder_6.append("<dependency>");
      _builder_6.newLine();
      _builder_6.append("    ");
      _builder_6.append("<groupId>org.springframework.boot</groupId>");
      _builder_6.newLine();
      _builder_6.append("    ");
      _builder_6.append("<artifactId>spring-boot-starter-data-mongodb</artifactId>");
      _builder_6.newLine();
      _builder_6.append("</dependency>");
      _builder_6.newLine();
      Pair<String, String> _mappedTo_6 = Pair.<String, String>of("SpringDataMongoDB", _builder_6.toString());
      StringConcatenation _builder_7 = new StringConcatenation();
      _builder_7.append("<dependency>");
      _builder_7.newLine();
      _builder_7.append("    ");
      _builder_7.append("<groupId>org.springframework.boot</groupId>");
      _builder_7.newLine();
      _builder_7.append("    ");
      _builder_7.append("<artifactId>spring-boot-starter-data-redis</artifactId>");
      _builder_7.newLine();
      _builder_7.append("</dependency>");
      _builder_7.newLine();
      Pair<String, String> _mappedTo_7 = Pair.<String, String>of("SpringDataRedis", _builder_7.toString());
      StringConcatenation _builder_8 = new StringConcatenation();
      _builder_8.append("<dependency>");
      _builder_8.newLine();
      _builder_8.append("    ");
      _builder_8.append("<groupId>org.springframework.boot</groupId>");
      _builder_8.newLine();
      _builder_8.append("    ");
      _builder_8.append("<artifactId>spring-boot-starter-data-rest</artifactId>");
      _builder_8.newLine();
      _builder_8.append("</dependency>");
      _builder_8.newLine();
      Pair<String, String> _mappedTo_8 = Pair.<String, String>of("SpringDataRest", _builder_8.toString());
      StringConcatenation _builder_9 = new StringConcatenation();
      _builder_9.append("<dependency>");
      _builder_9.newLine();
      _builder_9.append("    ");
      _builder_9.append("<groupId>org.springframework.boot</groupId>");
      _builder_9.newLine();
      _builder_9.append("    ");
      _builder_9.append("<artifactId>spring-boot-starter-graphql</artifactId>");
      _builder_9.newLine();
      _builder_9.append("</dependency>");
      _builder_9.newLine();
      Pair<String, String> _mappedTo_9 = Pair.<String, String>of("SpringGraphQL", _builder_9.toString());
      StringConcatenation _builder_10 = new StringConcatenation();
      _builder_10.append("<dependency>");
      _builder_10.newLine();
      _builder_10.append("    ");
      _builder_10.append("<groupId>org.springframework.boot</groupId>");
      _builder_10.newLine();
      _builder_10.append("    ");
      _builder_10.append("<artifactId>spring-boot-starter-integration</artifactId>");
      _builder_10.newLine();
      _builder_10.append("</dependency>");
      _builder_10.newLine();
      Pair<String, String> _mappedTo_10 = Pair.<String, String>of("SpringIntegration", _builder_10.toString());
      StringConcatenation _builder_11 = new StringConcatenation();
      _builder_11.append("<dependency>");
      _builder_11.newLine();
      _builder_11.append("    ");
      _builder_11.append("<groupId>org.springframework.boot</groupId>");
      _builder_11.newLine();
      _builder_11.append("    ");
      _builder_11.append("<artifactId>spring-boot-starter-jdbc</artifactId>");
      _builder_11.newLine();
      _builder_11.append("</dependency>");
      _builder_11.newLine();
      Pair<String, String> _mappedTo_11 = Pair.<String, String>of("SpringJDBC", _builder_11.toString());
      StringConcatenation _builder_12 = new StringConcatenation();
      _builder_12.append("<dependency>");
      _builder_12.newLine();
      _builder_12.append("    ");
      _builder_12.append("<groupId>org.springframework.boot</groupId>");
      _builder_12.newLine();
      _builder_12.append("    ");
      _builder_12.append("<artifactId>spring-boot-starter-jersey</artifactId>");
      _builder_12.newLine();
      _builder_12.append("</dependency>");
      _builder_12.newLine();
      Pair<String, String> _mappedTo_12 = Pair.<String, String>of("SpringJersey", _builder_12.toString());
      StringConcatenation _builder_13 = new StringConcatenation();
      _builder_13.append("<dependency>");
      _builder_13.newLine();
      _builder_13.append("    ");
      _builder_13.append("<groupId>org.springframework.boot</groupId>");
      _builder_13.newLine();
      _builder_13.append("    ");
      _builder_13.append("<artifactId>spring-boot-starter-oauth2-client</artifactId>");
      _builder_13.newLine();
      _builder_13.append("</dependency>");
      _builder_13.newLine();
      Pair<String, String> _mappedTo_13 = Pair.<String, String>of("SpringOAuth2Client", _builder_13.toString());
      StringConcatenation _builder_14 = new StringConcatenation();
      _builder_14.append("<dependency>");
      _builder_14.newLine();
      _builder_14.append("    ");
      _builder_14.append("<groupId>org.springframework.boot</groupId>");
      _builder_14.newLine();
      _builder_14.append("    ");
      _builder_14.append("<artifactId>spring-boot-starter-security</artifactId>");
      _builder_14.newLine();
      _builder_14.append("</dependency>");
      _builder_14.newLine();
      Pair<String, String> _mappedTo_14 = Pair.<String, String>of("SpringSecurity", _builder_14.toString());
      StringConcatenation _builder_15 = new StringConcatenation();
      _builder_15.append("<dependency>");
      _builder_15.newLine();
      _builder_15.append("    ");
      _builder_15.append("<groupId>org.springframework.boot</groupId>");
      _builder_15.newLine();
      _builder_15.append("    ");
      _builder_15.append("<artifactId>spring-boot-starter-thymeleaf</artifactId>");
      _builder_15.newLine();
      _builder_15.append("</dependency>");
      _builder_15.newLine();
      Pair<String, String> _mappedTo_15 = Pair.<String, String>of("SpringThymeleaf", _builder_15.toString());
      StringConcatenation _builder_16 = new StringConcatenation();
      _builder_16.append("<dependency>");
      _builder_16.newLine();
      _builder_16.append("    ");
      _builder_16.append("<groupId>org.springframework.boot</groupId>");
      _builder_16.newLine();
      _builder_16.append("    ");
      _builder_16.append("<artifactId>spring-boot-starter-validation</artifactId>");
      _builder_16.newLine();
      _builder_16.append("</dependency>");
      _builder_16.newLine();
      Pair<String, String> _mappedTo_16 = Pair.<String, String>of("SpringValidation", _builder_16.toString());
      StringConcatenation _builder_17 = new StringConcatenation();
      _builder_17.append("<dependency>");
      _builder_17.newLine();
      _builder_17.append("    ");
      _builder_17.append("<groupId>org.springframework.boot</groupId>");
      _builder_17.newLine();
      _builder_17.append("    ");
      _builder_17.append("<artifactId>spring-boot-starter-web</artifactId>");
      _builder_17.newLine();
      _builder_17.append("</dependency>");
      _builder_17.newLine();
      Pair<String, String> _mappedTo_17 = Pair.<String, String>of("SpringWeb", _builder_17.toString());
      StringConcatenation _builder_18 = new StringConcatenation();
      _builder_18.append("<dependency>");
      _builder_18.newLine();
      _builder_18.append("    ");
      _builder_18.append("<groupId>org.springframework.boot</groupId>");
      _builder_18.newLine();
      _builder_18.append("    ");
      _builder_18.append("<artifactId>spring-boot-starter-web-services</artifactId>");
      _builder_18.newLine();
      _builder_18.append("</dependency>");
      _builder_18.newLine();
      Pair<String, String> _mappedTo_18 = Pair.<String, String>of("SpringWebServices", _builder_18.toString());
      StringConcatenation _builder_19 = new StringConcatenation();
      _builder_19.append("<dependency>");
      _builder_19.newLine();
      _builder_19.append("    ");
      _builder_19.append("<groupId>org.springframework.boot</groupId>");
      _builder_19.newLine();
      _builder_19.append("    ");
      _builder_19.append("<artifactId>spring-boot-starter-webflux</artifactId>");
      _builder_19.newLine();
      _builder_19.append("</dependency>");
      _builder_19.newLine();
      Pair<String, String> _mappedTo_19 = Pair.<String, String>of("SpringWebFlux", _builder_19.toString());
      StringConcatenation _builder_20 = new StringConcatenation();
      _builder_20.append("<dependency>");
      _builder_20.newLine();
      _builder_20.append("    ");
      _builder_20.append("<groupId>org.springframework.integration</groupId>");
      _builder_20.newLine();
      _builder_20.append("    ");
      _builder_20.append("<artifactId>spring-integration-amqp</artifactId>");
      _builder_20.newLine();
      _builder_20.append("</dependency>");
      _builder_20.newLine();
      Pair<String, String> _mappedTo_20 = Pair.<String, String>of("SpringIntegrationAMQP", _builder_20.toString());
      StringConcatenation _builder_21 = new StringConcatenation();
      _builder_21.append("<dependency>");
      _builder_21.newLine();
      _builder_21.append("    ");
      _builder_21.append("<groupId>org.springframework.integration</groupId>");
      _builder_21.newLine();
      _builder_21.append("    ");
      _builder_21.append("<artifactId>spring-integration-http</artifactId>");
      _builder_21.newLine();
      _builder_21.append("</dependency>");
      _builder_21.newLine();
      Pair<String, String> _mappedTo_21 = Pair.<String, String>of("SpringIntegrationHTTP", _builder_21.toString());
      StringConcatenation _builder_22 = new StringConcatenation();
      _builder_22.append("<dependency>");
      _builder_22.newLine();
      _builder_22.append("    ");
      _builder_22.append("<groupId>org.springframework.integration</groupId>");
      _builder_22.newLine();
      _builder_22.append("    ");
      _builder_22.append("<artifactId>spring-integration-jdbc</artifactId>");
      _builder_22.newLine();
      _builder_22.append("</dependency>");
      _builder_22.newLine();
      Pair<String, String> _mappedTo_22 = Pair.<String, String>of("SpringIntegrationJDBC", _builder_22.toString());
      StringConcatenation _builder_23 = new StringConcatenation();
      _builder_23.append("<dependency>");
      _builder_23.newLine();
      _builder_23.append("    ");
      _builder_23.append("<groupId>org.springframework.integration</groupId>");
      _builder_23.newLine();
      _builder_23.append("    ");
      _builder_23.append("<artifactId>spring-integration-jpa</artifactId>");
      _builder_23.newLine();
      _builder_23.append("</dependency>");
      _builder_23.newLine();
      Pair<String, String> _mappedTo_23 = Pair.<String, String>of("SpringIntegrationJPA", _builder_23.toString());
      StringConcatenation _builder_24 = new StringConcatenation();
      _builder_24.append("<dependency>");
      _builder_24.newLine();
      _builder_24.append("    ");
      _builder_24.append("<groupId>org.springframework.integration</groupId>");
      _builder_24.newLine();
      _builder_24.append("    ");
      _builder_24.append("<artifactId>spring-integration-kafka</artifactId>");
      _builder_24.newLine();
      _builder_24.append("</dependency>");
      _builder_24.newLine();
      Pair<String, String> _mappedTo_24 = Pair.<String, String>of("SpringIntegrationKafka", _builder_24.toString());
      StringConcatenation _builder_25 = new StringConcatenation();
      _builder_25.append("<dependency>");
      _builder_25.newLine();
      _builder_25.append("    ");
      _builder_25.append("<groupId>org.springframework.integration</groupId>");
      _builder_25.newLine();
      _builder_25.append("    ");
      _builder_25.append("<artifactId>spring-integration-mongodb</artifactId>");
      _builder_25.newLine();
      _builder_25.append("</dependency>");
      _builder_25.newLine();
      Pair<String, String> _mappedTo_25 = Pair.<String, String>of("SpringIntegrationMongoDB", _builder_25.toString());
      StringConcatenation _builder_26 = new StringConcatenation();
      _builder_26.append("<dependency>");
      _builder_26.newLine();
      _builder_26.append("    ");
      _builder_26.append("<groupId>org.springframework.integration</groupId>");
      _builder_26.newLine();
      _builder_26.append("    ");
      _builder_26.append("<artifactId>spring-integration-redis</artifactId>");
      _builder_26.newLine();
      _builder_26.append("</dependency>");
      _builder_26.newLine();
      Pair<String, String> _mappedTo_26 = Pair.<String, String>of("SpringIntegrationRedis", _builder_26.toString());
      StringConcatenation _builder_27 = new StringConcatenation();
      _builder_27.append("<dependency>");
      _builder_27.newLine();
      _builder_27.append("    ");
      _builder_27.append("<groupId>org.springframework.integration</groupId>");
      _builder_27.newLine();
      _builder_27.append("    ");
      _builder_27.append("<artifactId>spring-integration-security</artifactId>");
      _builder_27.newLine();
      _builder_27.append("</dependency>");
      _builder_27.newLine();
      Pair<String, String> _mappedTo_27 = Pair.<String, String>of("SpringIntegrationSecurity", _builder_27.toString());
      StringConcatenation _builder_28 = new StringConcatenation();
      _builder_28.append("<dependency>");
      _builder_28.newLine();
      _builder_28.append("    ");
      _builder_28.append("<groupId>org.springframework.integration</groupId>");
      _builder_28.newLine();
      _builder_28.append("    ");
      _builder_28.append("<artifactId>spring-integration-webflux</artifactId>");
      _builder_28.newLine();
      _builder_28.append("</dependency>");
      _builder_28.newLine();
      Pair<String, String> _mappedTo_28 = Pair.<String, String>of("SpringIntegrationWebFlux", _builder_28.toString());
      StringConcatenation _builder_29 = new StringConcatenation();
      _builder_29.append("<dependency>");
      _builder_29.newLine();
      _builder_29.append("    ");
      _builder_29.append("<groupId>org.springframework.boot</groupId>");
      _builder_29.newLine();
      _builder_29.append("    ");
      _builder_29.append("<artifactId>spring-boot-devtools</artifactId>");
      _builder_29.newLine();
      _builder_29.append("    ");
      _builder_29.append("<version>3.2.0</version>");
      _builder_29.newLine();
      _builder_29.append("</dependency>");
      _builder_29.newLine();
      Pair<String, String> _mappedTo_29 = Pair.<String, String>of("DevTools", _builder_29.toString());
      StringConcatenation _builder_30 = new StringConcatenation();
      _builder_30.append("dependency>");
      _builder_30.newLine();
      _builder_30.append("\t\t\t");
      _builder_30.append("<groupId>org.springdoc</groupId>");
      _builder_30.newLine();
      _builder_30.append("\t\t\t");
      _builder_30.append("<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>");
      _builder_30.newLine();
      _builder_30.append("\t\t\t");
      _builder_30.append("<version>2.2.0</version>");
      _builder_30.newLine();
      _builder_30.append("\t\t");
      _builder_30.append("</dependency>");
      _builder_30.newLine();
      Pair<String, String> _mappedTo_30 = Pair.<String, String>of("Swagger", _builder_30.toString());
      StringConcatenation _builder_31 = new StringConcatenation();
      _builder_31.append("<dependency>");
      _builder_31.newLine();
      _builder_31.append("    ");
      _builder_31.append("<groupId>org.springframework.integration</groupId>");
      _builder_31.newLine();
      _builder_31.append("    ");
      _builder_31.append("<artifactId>spring-integration-ws</artifactId>");
      _builder_31.newLine();
      _builder_31.append("</dependency>");
      _builder_31.newLine();
      Pair<String, String> _mappedTo_31 = Pair.<String, String>of("SpringIntegrationWS", _builder_31.toString());
      StringConcatenation _builder_32 = new StringConcatenation();
      _builder_32.append("<dependency>");
      _builder_32.newLine();
      _builder_32.append("    ");
      _builder_32.append("<groupId>org.springframework.kafka</groupId>");
      _builder_32.newLine();
      _builder_32.append("    ");
      _builder_32.append("<artifactId>spring-kafka</artifactId>");
      _builder_32.newLine();
      _builder_32.append("</dependency>");
      _builder_32.newLine();
      Pair<String, String> _mappedTo_32 = Pair.<String, String>of("SpringKafka", _builder_32.toString());
      StringConcatenation _builder_33 = new StringConcatenation();
      _builder_33.append("<dependency>");
      _builder_33.newLine();
      _builder_33.append("    ");
      _builder_33.append("<groupId>org.thymeleaf.extras</groupId>");
      _builder_33.newLine();
      _builder_33.append("    ");
      _builder_33.append("<artifactId>thymeleaf-extras-springsecurity6</artifactId>");
      _builder_33.newLine();
      _builder_33.append("</dependency>");
      _builder_33.newLine();
      Pair<String, String> _mappedTo_33 = Pair.<String, String>of("ThymeleafExtras", _builder_33.toString());
      StringConcatenation _builder_34 = new StringConcatenation();
      _builder_34.append("<dependency>");
      _builder_34.newLine();
      _builder_34.append("    ");
      _builder_34.append("<groupId>org.springframework.boot</groupId>");
      _builder_34.newLine();
      _builder_34.append("    ");
      _builder_34.append("<artifactId>spring-boot-devtools</artifactId>");
      _builder_34.newLine();
      _builder_34.append("    ");
      _builder_34.append("<scope>runtime</scope>");
      _builder_34.newLine();
      _builder_34.append("    ");
      _builder_34.append("<optional>true</optional>");
      _builder_34.newLine();
      _builder_34.append("</dependency>");
      _builder_34.newLine();
      Pair<String, String> _mappedTo_34 = Pair.<String, String>of("SpringDevTools", _builder_34.toString());
      StringConcatenation _builder_35 = new StringConcatenation();
      _builder_35.append("<dependency>");
      _builder_35.newLine();
      _builder_35.append("    ");
      _builder_35.append("<groupId>com.h2database</groupId>");
      _builder_35.newLine();
      _builder_35.append("    ");
      _builder_35.append("<artifactId>h2</artifactId>");
      _builder_35.newLine();
      _builder_35.append("    ");
      _builder_35.append("<scope>runtime</scope>");
      _builder_35.newLine();
      _builder_35.append("</dependency>");
      _builder_35.newLine();
      Pair<String, String> _mappedTo_35 = Pair.<String, String>of("H2Database", _builder_35.toString());
      StringConcatenation _builder_36 = new StringConcatenation();
      _builder_36.append("<dependency>");
      _builder_36.newLine();
      _builder_36.append("    ");
      _builder_36.append("<groupId>com.mysql</groupId>");
      _builder_36.newLine();
      _builder_36.append("    ");
      _builder_36.append("<artifactId>mysql-connector-j</artifactId>");
      _builder_36.newLine();
      _builder_36.append("    ");
      _builder_36.append("<scope>runtime</scope>");
      _builder_36.newLine();
      _builder_36.append("</dependency>");
      _builder_36.newLine();
      Pair<String, String> _mappedTo_36 = Pair.<String, String>of("MySQLConnector", _builder_36.toString());
      StringConcatenation _builder_37 = new StringConcatenation();
      _builder_37.append("<dependency>");
      _builder_37.newLine();
      _builder_37.append("    ");
      _builder_37.append("<groupId>com.oracle.database.jdbc</groupId>");
      _builder_37.newLine();
      _builder_37.append("    ");
      _builder_37.append("<artifactId>ojdbc11</artifactId>");
      _builder_37.newLine();
      _builder_37.append("    ");
      _builder_37.append("<scope>runtime</scope>");
      _builder_37.newLine();
      _builder_37.append("</dependency>");
      _builder_37.newLine();
      Pair<String, String> _mappedTo_37 = Pair.<String, String>of("OracleJDBC", _builder_37.toString());
      StringConcatenation _builder_38 = new StringConcatenation();
      _builder_38.append("<dependency>");
      _builder_38.newLine();
      _builder_38.append("    ");
      _builder_38.append("<groupId>org.mariadb.jdbc</groupId>");
      _builder_38.newLine();
      _builder_38.append("    ");
      _builder_38.append("<artifactId>mariadb-java-client</artifactId>");
      _builder_38.newLine();
      _builder_38.append("    ");
      _builder_38.append("<scope>runtime</scope>");
      _builder_38.newLine();
      _builder_38.append("</dependency>");
      _builder_38.newLine();
      Pair<String, String> _mappedTo_38 = Pair.<String, String>of("MariaDBConnector", _builder_38.toString());
      StringConcatenation _builder_39 = new StringConcatenation();
      _builder_39.append("<dependency>");
      _builder_39.newLine();
      _builder_39.append("    ");
      _builder_39.append("<groupId>org.postgresql</groupId>");
      _builder_39.newLine();
      _builder_39.append("    ");
      _builder_39.append("<artifactId>postgresql</artifactId>");
      _builder_39.newLine();
      _builder_39.append("    ");
      _builder_39.append("<scope>runtime</scope>");
      _builder_39.newLine();
      _builder_39.append("</dependency>");
      _builder_39.newLine();
      Pair<String, String> _mappedTo_39 = Pair.<String, String>of("PostgreSQL", _builder_39.toString());
      StringConcatenation _builder_40 = new StringConcatenation();
      _builder_40.append("<dependency>");
      _builder_40.newLine();
      _builder_40.append("    ");
      _builder_40.append("<groupId>org.projectlombok</groupId>");
      _builder_40.newLine();
      _builder_40.append("    ");
      _builder_40.append("<artifactId>lombok</artifactId>");
      _builder_40.newLine();
      _builder_40.append("    ");
      _builder_40.append("<optional>true</optional>");
      _builder_40.newLine();
      _builder_40.append("</dependency>");
      _builder_40.newLine();
      Pair<String, String> _mappedTo_40 = Pair.<String, String>of("Lombok", _builder_40.toString());
      StringConcatenation _builder_41 = new StringConcatenation();
      _builder_41.append("<dependency>");
      _builder_41.newLine();
      _builder_41.append("    ");
      _builder_41.append("<groupId>org.springframework.boot</groupId>");
      _builder_41.newLine();
      _builder_41.append("    ");
      _builder_41.append("<artifactId>spring-boot-starter-test</artifactId>");
      _builder_41.newLine();
      _builder_41.append("    ");
      _builder_41.append("<scope>test</scope>");
      _builder_41.newLine();
      _builder_41.append("</dependency>");
      _builder_41.newLine();
      Pair<String, String> _mappedTo_41 = Pair.<String, String>of("SpringBootTest", _builder_41.toString());
      StringConcatenation _builder_42 = new StringConcatenation();
      _builder_42.append("<dependency>");
      _builder_42.newLine();
      _builder_42.append("    ");
      _builder_42.append("<groupId>io.projectreactor</groupId>");
      _builder_42.newLine();
      _builder_42.append("    ");
      _builder_42.append("<artifactId>reactor-test</artifactId>");
      _builder_42.newLine();
      _builder_42.append("    ");
      _builder_42.append("<scope>test</scope>");
      _builder_42.newLine();
      _builder_42.append("</dependency>");
      _builder_42.newLine();
      Pair<String, String> _mappedTo_42 = Pair.<String, String>of("ReactorTest", _builder_42.toString());
      StringConcatenation _builder_43 = new StringConcatenation();
      _builder_43.append("<dependency>");
      _builder_43.newLine();
      _builder_43.append("    ");
      _builder_43.append("<groupId>org.springframework.amqp</groupId>");
      _builder_43.newLine();
      _builder_43.append("    ");
      _builder_43.append("<artifactId>spring-rabbit-test</artifactId>");
      _builder_43.newLine();
      _builder_43.append("    ");
      _builder_43.append("<scope>test</scope>");
      _builder_43.newLine();
      _builder_43.append("</dependency>");
      _builder_43.newLine();
      Pair<String, String> _mappedTo_43 = Pair.<String, String>of("SpringRabbitTest", _builder_43.toString());
      StringConcatenation _builder_44 = new StringConcatenation();
      _builder_44.append("<dependency>");
      _builder_44.newLine();
      _builder_44.append("    ");
      _builder_44.append("<groupId>org.springframework.batch</groupId>");
      _builder_44.newLine();
      _builder_44.append("    ");
      _builder_44.append("<artifactId>spring-batch-test</artifactId>");
      _builder_44.newLine();
      _builder_44.append("    ");
      _builder_44.append("<scope>test</scope>");
      _builder_44.newLine();
      _builder_44.append("</dependency>");
      _builder_44.newLine();
      Pair<String, String> _mappedTo_44 = Pair.<String, String>of("SpringBatchTest", _builder_44.toString());
      StringConcatenation _builder_45 = new StringConcatenation();
      _builder_45.append("<dependency>");
      _builder_45.newLine();
      _builder_45.append("    ");
      _builder_45.append("<groupId>org.springframework.graphql</groupId>");
      _builder_45.newLine();
      _builder_45.append("    ");
      _builder_45.append("<artifactId>spring-graphql-test</artifactId>");
      _builder_45.newLine();
      _builder_45.append("    ");
      _builder_45.append("<scope>test</scope>");
      _builder_45.newLine();
      _builder_45.append("</dependency>");
      _builder_45.newLine();
      Pair<String, String> _mappedTo_45 = Pair.<String, String>of("SpringGraphQLTest", _builder_45.toString());
      StringConcatenation _builder_46 = new StringConcatenation();
      _builder_46.append("<dependency>");
      _builder_46.newLine();
      _builder_46.append("    ");
      _builder_46.append("<groupId>org.springframework.integration</groupId>");
      _builder_46.newLine();
      _builder_46.append("    ");
      _builder_46.append("<artifactId>spring-integration-test</artifactId>");
      _builder_46.newLine();
      _builder_46.append("    ");
      _builder_46.append("<scope>test</scope>");
      _builder_46.newLine();
      _builder_46.append("</dependency>");
      _builder_46.newLine();
      Pair<String, String> _mappedTo_46 = Pair.<String, String>of("SpringIntegrationTest", _builder_46.toString());
      StringConcatenation _builder_47 = new StringConcatenation();
      _builder_47.append("<dependency>");
      _builder_47.newLine();
      _builder_47.append("    ");
      _builder_47.append("<groupId>org.springframework.kafka</groupId>");
      _builder_47.newLine();
      _builder_47.append("    ");
      _builder_47.append("<artifactId>spring-kafka-test</artifactId>");
      _builder_47.newLine();
      _builder_47.append("    ");
      _builder_47.append("<scope>test</scope>");
      _builder_47.newLine();
      _builder_47.append("</dependency>");
      _builder_47.newLine();
      Pair<String, String> _mappedTo_47 = Pair.<String, String>of("SpringKafkaTest", _builder_47.toString());
      StringConcatenation _builder_48 = new StringConcatenation();
      _builder_48.append("<dependency>");
      _builder_48.newLine();
      _builder_48.append("    ");
      _builder_48.append("<groupId>org.springframework.security</groupId>");
      _builder_48.newLine();
      _builder_48.append("    ");
      _builder_48.append("<artifactId>spring-security-test</artifactId>");
      _builder_48.newLine();
      _builder_48.append("    ");
      _builder_48.append("<scope>test</scope>");
      _builder_48.newLine();
      _builder_48.append("</dependency>");
      _builder_48.newLine();
      Pair<String, String> _mappedTo_48 = Pair.<String, String>of("SpringSecurityTest", _builder_48.toString());
      HashMap<String, String> _newHashMap = CollectionLiterals.<String, String>newHashMap(_mappedTo, _mappedTo_1, _mappedTo_2, _mappedTo_3, _mappedTo_4, _mappedTo_5, _mappedTo_6, _mappedTo_7, _mappedTo_8, _mappedTo_9, _mappedTo_10, _mappedTo_11, _mappedTo_12, _mappedTo_13, _mappedTo_14, _mappedTo_15, _mappedTo_16, _mappedTo_17, _mappedTo_18, _mappedTo_19, _mappedTo_20, _mappedTo_21, _mappedTo_22, _mappedTo_23, _mappedTo_24, _mappedTo_25, _mappedTo_26, _mappedTo_27, _mappedTo_28, _mappedTo_29, _mappedTo_30, _mappedTo_31, _mappedTo_32, _mappedTo_33, _mappedTo_34, _mappedTo_35, _mappedTo_36, _mappedTo_37, _mappedTo_38, _mappedTo_39, _mappedTo_40, _mappedTo_41, _mappedTo_42, _mappedTo_43, _mappedTo_44, _mappedTo_45, _mappedTo_46, _mappedTo_47, _mappedTo_48);
      return _newHashMap;
    }
  }.apply();

  public void generateDependencies(final Dependencies dependencies, final IFileSystemAccess2 fsa) {
    final CharSequence existingContent = fsa.readTextFile("pom.xml");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<dependencies>");
    _builder.newLine();
    final Function1<Dependency, String> _function = (Dependency it) -> {
      return this.generateDependency(it);
    };
    String _join = IterableExtensions.join(ListExtensions.<Dependency, String>map(dependencies.getDependencies(), _function), "\n");
    String _plus = (_builder.toString() + _join);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("</dependencies>");
    _builder_1.newLine();
    _builder_1.append("<build>");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("<plugins>");
    _builder_1.newLine();
    _builder_1.append("\t\t\t");
    _builder_1.append("<plugin>");
    _builder_1.newLine();
    _builder_1.append("\t\t\t\t");
    _builder_1.append("<groupId>org.springframework.boot</groupId>");
    _builder_1.newLine();
    _builder_1.append("\t\t\t\t");
    _builder_1.append("<artifactId>spring-boot-maven-plugin</artifactId>");
    _builder_1.newLine();
    _builder_1.append("\t\t\t");
    _builder_1.append("</plugin>");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("</plugins>");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("</build>");
    _builder_1.newLine();
    _builder_1.append("</project>");
    _builder_1.newLine();
    final String dependenciesContent = (_plus + _builder_1);
    String _plus_1 = (existingContent + "\n");
    String _plus_2 = (_plus_1 + dependenciesContent);
    fsa.generateFile("pom.xml", _plus_2);
  }

  public String generateDependency(final Dependency dependency) {
    final String content = DependenciesGenerator.dependenciesMap.get(dependency.getDependency().toString());
    String _xifexpression = null;
    boolean _notEquals = (!Objects.equal(content, null));
    if (_notEquals) {
      _xifexpression = content;
    } else {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<!-- Unsupported dependency type: ${dependency.dependency} -->");
      _builder.newLine();
      _xifexpression = _builder.toString();
    }
    return _xifexpression;
  }
}
