/*
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.spring.fluent.ui.internal.FluentActivator;

public class SpringFluentDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FluentActivator.getInstance().getInjector("org.xtext.spring.fluent.SpringFluentDSL");
	}

}
