/*
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.spring.fluent.ui.internal.FluentActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpringFluentDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FluentActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FluentActivator activator = FluentActivator.getInstance();
		return activator != null ? activator.getInjector(FluentActivator.ORG_XTEXT_SPRING_FLUENT_SPRINGFLUENTDSL) : null;
	}

}
