/**
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.springFluentDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Dependency#getDependency <em>Dependency</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getDependency()
 * @model
 * @generated
 */
public interface Dependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Dependency</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.spring.fluent.springFluentDSL.DependencyType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependency</em>' attribute.
   * @see org.xtext.spring.fluent.springFluentDSL.DependencyType
   * @see #setDependency(DependencyType)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getDependency_Dependency()
   * @model
   * @generated
   */
  DependencyType getDependency();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.Dependency#getDependency <em>Dependency</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dependency</em>' attribute.
   * @see org.xtext.spring.fluent.springFluentDSL.DependencyType
   * @see #getDependency()
   * @generated
   */
  void setDependency(DependencyType value);

} // Dependency
