/**
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.springFluentDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Feature#getOperation <em>Operation</em>}</li>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Feature#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Feature#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Feature#getRelations <em>Relations</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference.
   * @see #setOperation(Operation)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getFeature_Operation()
   * @model containment="true"
   * @generated
   */
  Operation getOperation();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.Feature#getOperation <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' containment reference.
   * @see #getOperation()
   * @generated
   */
  void setOperation(Operation value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(IDENTITY)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getFeature_Id()
   * @model containment="true"
   * @generated
   */
  IDENTITY getId();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.Feature#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(IDENTITY value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.spring.fluent.springFluentDSL.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getFeature_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.spring.fluent.springFluentDSL.Relation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations</em>' containment reference list.
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getFeature_Relations()
   * @model containment="true"
   * @generated
   */
  EList<Relation> getRelations();

} // Feature
