/**
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.springFluentDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Model#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Model#getAppName <em>App Name</em>}</li>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Model#getDependencies <em>Dependencies</em>}</li>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Model#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' containment reference.
   * @see #setPrefix(Prefix)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getModel_Prefix()
   * @model containment="true"
   * @generated
   */
  Prefix getPrefix();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.Model#getPrefix <em>Prefix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' containment reference.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(Prefix value);

  /**
   * Returns the value of the '<em><b>App Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>App Name</em>' containment reference.
   * @see #setAppName(AppName)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getModel_AppName()
   * @model containment="true"
   * @generated
   */
  AppName getAppName();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.Model#getAppName <em>App Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>App Name</em>' containment reference.
   * @see #getAppName()
   * @generated
   */
  void setAppName(AppName value);

  /**
   * Returns the value of the '<em><b>Dependencies</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencies</em>' containment reference.
   * @see #setDependencies(Dependencies)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getModel_Dependencies()
   * @model containment="true"
   * @generated
   */
  Dependencies getDependencies();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.Model#getDependencies <em>Dependencies</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dependencies</em>' containment reference.
   * @see #getDependencies()
   * @generated
   */
  void setDependencies(Dependencies value);

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference.
   * @see #setEntities(Entities)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getModel_Entities()
   * @model containment="true"
   * @generated
   */
  Entities getEntities();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.Model#getEntities <em>Entities</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entities</em>' containment reference.
   * @see #getEntities()
   * @generated
   */
  void setEntities(Entities value);

} // Model
