/**
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.springFluentDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.OperationType#getOprationType <em>Opration Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getOperationType()
 * @model
 * @generated
 */
public interface OperationType extends Operation
{
  /**
   * Returns the value of the '<em><b>Opration Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opration Type</em>' attribute.
   * @see #setOprationType(String)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getOperationType_OprationType()
   * @model
   * @generated
   */
  String getOprationType();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.OperationType#getOprationType <em>Opration Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opration Type</em>' attribute.
   * @see #getOprationType()
   * @generated
   */
  void setOprationType(String value);

} // OperationType
