/**
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.springFluentDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLFactory
 * @model kind="package"
 * @generated
 */
public interface SpringFluentDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "springFluentDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/spring/fluent/SpringFluentDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "springFluentDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SpringFluentDSLPackage eINSTANCE = org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.ModelImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PREFIX = 0;

  /**
   * The feature id for the '<em><b>App Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__APP_NAME = 1;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DEPENDENCIES = 2;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTITIES = 3;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.PrefixImpl <em>Prefix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.PrefixImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getPrefix()
   * @generated
   */
  int PREFIX = 1;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX__PREFIX = 0;

  /**
   * The number of structural features of the '<em>Prefix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.AppNameImpl <em>App Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.AppNameImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getAppName()
   * @generated
   */
  int APP_NAME = 2;

  /**
   * The feature id for the '<em><b>App Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_NAME__APP_NAME = 0;

  /**
   * The number of structural features of the '<em>App Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APP_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.DependenciesImpl <em>Dependencies</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.DependenciesImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getDependencies()
   * @generated
   */
  int DEPENDENCIES = 3;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCIES__DEPENDENCIES = 0;

  /**
   * The number of structural features of the '<em>Dependencies</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCIES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.DependencyImpl <em>Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.DependencyImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getDependency()
   * @generated
   */
  int DEPENDENCY = 4;

  /**
   * The feature id for the '<em><b>Dependency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__DEPENDENCY = 0;

  /**
   * The number of structural features of the '<em>Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.EntitiesImpl <em>Entities</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.EntitiesImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getEntities()
   * @generated
   */
  int ENTITIES = 5;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITIES__ENTITIES = 0;

  /**
   * The number of structural features of the '<em>Entities</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITIES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.EntityImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Strategy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__STRATEGY = 1;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__SUPER_TYPE = 2;

  /**
   * The feature id for the '<em><b>Feature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__FEATURE = 3;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.FeatureImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 7;

  /**
   * The feature id for the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__OPERATION = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__ID = 1;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__ATTRIBUTES = 2;

  /**
   * The feature id for the '<em><b>Relations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__RELATIONS = 3;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.StrategyImpl <em>Strategy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.StrategyImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getStrategy()
   * @generated
   */
  int STRATEGY = 8;

  /**
   * The feature id for the '<em><b>Strategy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY__STRATEGY = 0;

  /**
   * The number of structural features of the '<em>Strategy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.IDENTITYImpl <em>IDENTITY</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.IDENTITYImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getIDENTITY()
   * @generated
   */
  int IDENTITY = 9;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTITY__TYPE = 0;

  /**
   * The number of structural features of the '<em>IDENTITY</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.OperationImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 10;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.OperationTypeImpl <em>Operation Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.OperationTypeImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getOperationType()
   * @generated
   */
  int OPERATION_TYPE = 11;

  /**
   * The feature id for the '<em><b>Opration Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_TYPE__OPRATION_TYPE = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Operation Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_TYPE_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.AttributeImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.impl.RelationImpl
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__TARGET = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__TYPE = 2;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.DependencyType <em>Dependency Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.DependencyType
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getDependencyType()
   * @generated
   */
  int DEPENDENCY_TYPE = 14;

  /**
   * The meta object id for the '{@link org.xtext.spring.fluent.springFluentDSL.Type <em>Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.spring.fluent.springFluentDSL.Type
   * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getType()
   * @generated
   */
  int TYPE = 15;


  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.spring.fluent.springFluentDSL.Model#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prefix</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Model#getPrefix()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Prefix();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.spring.fluent.springFluentDSL.Model#getAppName <em>App Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>App Name</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Model#getAppName()
   * @see #getModel()
   * @generated
   */
  EReference getModel_AppName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.spring.fluent.springFluentDSL.Model#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dependencies</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Model#getDependencies()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Dependencies();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.spring.fluent.springFluentDSL.Model#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entities</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Model#getEntities()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Entities();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Prefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prefix</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Prefix
   * @generated
   */
  EClass getPrefix();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.Prefix#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Prefix#getPrefix()
   * @see #getPrefix()
   * @generated
   */
  EAttribute getPrefix_Prefix();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.AppName <em>App Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>App Name</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.AppName
   * @generated
   */
  EClass getAppName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.AppName#getAppName <em>App Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>App Name</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.AppName#getAppName()
   * @see #getAppName()
   * @generated
   */
  EAttribute getAppName_AppName();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Dependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependencies</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Dependencies
   * @generated
   */
  EClass getDependencies();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.spring.fluent.springFluentDSL.Dependencies#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencies</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Dependencies#getDependencies()
   * @see #getDependencies()
   * @generated
   */
  EReference getDependencies_Dependencies();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Dependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Dependency
   * @generated
   */
  EClass getDependency();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.Dependency#getDependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dependency</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Dependency#getDependency()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Dependency();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Entities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entities</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Entities
   * @generated
   */
  EClass getEntities();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.spring.fluent.springFluentDSL.Entities#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Entities#getEntities()
   * @see #getEntities()
   * @generated
   */
  EReference getEntities_Entities();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.spring.fluent.springFluentDSL.Entity#getStrategy <em>Strategy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Strategy</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Entity#getStrategy()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Strategy();

  /**
   * Returns the meta object for the reference '{@link org.xtext.spring.fluent.springFluentDSL.Entity#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Entity#getSuperType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_SuperType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.spring.fluent.springFluentDSL.Entity#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Feature</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Entity#getFeature()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Feature();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.spring.fluent.springFluentDSL.Feature#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operation</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Feature#getOperation()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Operation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.spring.fluent.springFluentDSL.Feature#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Feature#getId()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Id();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.spring.fluent.springFluentDSL.Feature#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Feature#getAttributes()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.spring.fluent.springFluentDSL.Feature#getRelations <em>Relations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relations</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Feature#getRelations()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Relations();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Strategy <em>Strategy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strategy</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Strategy
   * @generated
   */
  EClass getStrategy();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.Strategy#getStrategy <em>Strategy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Strategy</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Strategy#getStrategy()
   * @see #getStrategy()
   * @generated
   */
  EAttribute getStrategy_Strategy();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.IDENTITY <em>IDENTITY</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IDENTITY</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.IDENTITY
   * @generated
   */
  EClass getIDENTITY();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.IDENTITY#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.IDENTITY#getType()
   * @see #getIDENTITY()
   * @generated
   */
  EAttribute getIDENTITY_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.OperationType <em>Operation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation Type</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.OperationType
   * @generated
   */
  EClass getOperationType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.OperationType#getOprationType <em>Opration Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Opration Type</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.OperationType#getOprationType()
   * @see #getOperationType()
   * @generated
   */
  EAttribute getOperationType_OprationType();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.spring.fluent.springFluentDSL.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.Relation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Relation#getName()
   * @see #getRelation()
   * @generated
   */
  EAttribute getRelation_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.spring.fluent.springFluentDSL.Relation#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Relation#getTarget()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Target();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.spring.fluent.springFluentDSL.Relation#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Relation#getType()
   * @see #getRelation()
   * @generated
   */
  EAttribute getRelation_Type();

  /**
   * Returns the meta object for enum '{@link org.xtext.spring.fluent.springFluentDSL.DependencyType <em>Dependency Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Dependency Type</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.DependencyType
   * @generated
   */
  EEnum getDependencyType();

  /**
   * Returns the meta object for enum '{@link org.xtext.spring.fluent.springFluentDSL.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type</em>'.
   * @see org.xtext.spring.fluent.springFluentDSL.Type
   * @generated
   */
  EEnum getType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SpringFluentDSLFactory getSpringFluentDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.ModelImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PREFIX = eINSTANCE.getModel_Prefix();

    /**
     * The meta object literal for the '<em><b>App Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__APP_NAME = eINSTANCE.getModel_AppName();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DEPENDENCIES = eINSTANCE.getModel_Dependencies();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTITIES = eINSTANCE.getModel_Entities();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.PrefixImpl <em>Prefix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.PrefixImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getPrefix()
     * @generated
     */
    EClass PREFIX = eINSTANCE.getPrefix();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFIX__PREFIX = eINSTANCE.getPrefix_Prefix();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.AppNameImpl <em>App Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.AppNameImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getAppName()
     * @generated
     */
    EClass APP_NAME = eINSTANCE.getAppName();

    /**
     * The meta object literal for the '<em><b>App Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APP_NAME__APP_NAME = eINSTANCE.getAppName_AppName();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.DependenciesImpl <em>Dependencies</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.DependenciesImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getDependencies()
     * @generated
     */
    EClass DEPENDENCIES = eINSTANCE.getDependencies();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCIES__DEPENDENCIES = eINSTANCE.getDependencies_Dependencies();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.DependencyImpl <em>Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.DependencyImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getDependency()
     * @generated
     */
    EClass DEPENDENCY = eINSTANCE.getDependency();

    /**
     * The meta object literal for the '<em><b>Dependency</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__DEPENDENCY = eINSTANCE.getDependency_Dependency();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.EntitiesImpl <em>Entities</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.EntitiesImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getEntities()
     * @generated
     */
    EClass ENTITIES = eINSTANCE.getEntities();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITIES__ENTITIES = eINSTANCE.getEntities_Entities();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.EntityImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '<em><b>Strategy</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__STRATEGY = eINSTANCE.getEntity_Strategy();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__SUPER_TYPE = eINSTANCE.getEntity_SuperType();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__FEATURE = eINSTANCE.getEntity_Feature();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.FeatureImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__OPERATION = eINSTANCE.getFeature_Operation();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__ID = eINSTANCE.getFeature_Id();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__ATTRIBUTES = eINSTANCE.getFeature_Attributes();

    /**
     * The meta object literal for the '<em><b>Relations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__RELATIONS = eINSTANCE.getFeature_Relations();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.StrategyImpl <em>Strategy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.StrategyImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getStrategy()
     * @generated
     */
    EClass STRATEGY = eINSTANCE.getStrategy();

    /**
     * The meta object literal for the '<em><b>Strategy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRATEGY__STRATEGY = eINSTANCE.getStrategy_Strategy();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.IDENTITYImpl <em>IDENTITY</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.IDENTITYImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getIDENTITY()
     * @generated
     */
    EClass IDENTITY = eINSTANCE.getIDENTITY();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IDENTITY__TYPE = eINSTANCE.getIDENTITY_Type();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.OperationImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.OperationTypeImpl <em>Operation Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.OperationTypeImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getOperationType()
     * @generated
     */
    EClass OPERATION_TYPE = eINSTANCE.getOperationType();

    /**
     * The meta object literal for the '<em><b>Opration Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION_TYPE__OPRATION_TYPE = eINSTANCE.getOperationType_OprationType();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.AttributeImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.impl.RelationImpl
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION__NAME = eINSTANCE.getRelation_Name();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__TARGET = eINSTANCE.getRelation_Target();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION__TYPE = eINSTANCE.getRelation_Type();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.DependencyType <em>Dependency Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.DependencyType
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getDependencyType()
     * @generated
     */
    EEnum DEPENDENCY_TYPE = eINSTANCE.getDependencyType();

    /**
     * The meta object literal for the '{@link org.xtext.spring.fluent.springFluentDSL.Type <em>Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.spring.fluent.springFluentDSL.Type
     * @see org.xtext.spring.fluent.springFluentDSL.impl.SpringFluentDSLPackageImpl#getType()
     * @generated
     */
    EEnum TYPE = eINSTANCE.getType();

  }

} //SpringFluentDSLPackage
