/**
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.springFluentDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Strategy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.spring.fluent.springFluentDSL.Strategy#getStrategy <em>Strategy</em>}</li>
 * </ul>
 *
 * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getStrategy()
 * @model
 * @generated
 */
public interface Strategy extends EObject
{
  /**
   * Returns the value of the '<em><b>Strategy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strategy</em>' attribute.
   * @see #setStrategy(String)
   * @see org.xtext.spring.fluent.springFluentDSL.SpringFluentDSLPackage#getStrategy_Strategy()
   * @model
   * @generated
   */
  String getStrategy();

  /**
   * Sets the value of the '{@link org.xtext.spring.fluent.springFluentDSL.Strategy#getStrategy <em>Strategy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strategy</em>' attribute.
   * @see #getStrategy()
   * @generated
   */
  void setStrategy(String value);

} // Strategy
