/*
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SpringFluentDSLUiModule extends AbstractSpringFluentDSLUiModule {

	public SpringFluentDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
