/*
 * generated by Xtext 2.32.0
 */
package org.xtext.spring.fluent.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpringFluentDSLScopeProvider extends DelegatingScopeProvider {
}
